#!/bin/sh /etc/rc.common
# (C) 2013 openwrt.org

START=99

boot() {
	/mnt/mmcblk2p4/NodeSpeed/go.sh
}

start() {
	/mnt/mmcblk2p4/NodeSpeed/go.sh
	return 0
}

restart() {
	/mnt/mmcblk2p4/NodeSpeed/go.sh
	return 0
}

stop() {
	echo stop
	#commands to kill application
	killall mixnode	
}
